version: '3.4'

services:
  assecopraksa:
    image: ${DOCKER_REGISTRY-}assecopraksa
    container_name: assecopraksa
    build:
      context: .
      dockerfile: AssecoPraksa/Dockerfile
    ports:
      - 5078:5078

  transactions.database:
    image: docker.io/bitnami/postgresql:11.11.0-debian-10-r62
    container_name: transactions.database
    environment:
      - POSTGRES_DB=transactions
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Password123#
    volumes:
      - ./.containers/transactions-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
