// <auto-generated />
using System;
using AssecoPraksa.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssecoPraksa.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20240729200425_AddTransactionSplitTable")]
    partial class AddTransactionSplitTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssecoPraksa.Database.Entities.CategoryEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParentCode")
                        .HasColumnType("text")
                        .HasColumnName("parent-code");

                    b.HasKey("Code");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("AssecoPraksa.Database.Entities.TransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("BeneficiaryName")
                        .HasColumnType("text")
                        .HasColumnName("beneficiary-name");

                    b.Property<string>("Catcode")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mcc")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("TransactionKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Catcode");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("AssecoPraksa.Database.Entities.TransactionSplitEntity", b =>
                {
                    b.Property<int>("SplitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("split-id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SplitId"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Catcode")
                        .HasColumnType("text");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction-id");

                    b.HasKey("SplitId");

                    b.HasIndex("Catcode");

                    b.HasIndex("TransactionId");

                    b.ToTable("transaction_splits", (string)null);
                });

            modelBuilder.Entity("AssecoPraksa.Database.Entities.TransactionEntity", b =>
                {
                    b.HasOne("AssecoPraksa.Database.Entities.CategoryEntity", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("Catcode");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AssecoPraksa.Database.Entities.TransactionSplitEntity", b =>
                {
                    b.HasOne("AssecoPraksa.Database.Entities.CategoryEntity", "Category")
                        .WithMany("TransactionSplits")
                        .HasForeignKey("Catcode");

                    b.HasOne("AssecoPraksa.Database.Entities.TransactionEntity", "Transaction")
                        .WithMany("TransactionSplits")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("AssecoPraksa.Database.Entities.CategoryEntity", b =>
                {
                    b.Navigation("TransactionSplits");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("AssecoPraksa.Database.Entities.TransactionEntity", b =>
                {
                    b.Navigation("TransactionSplits");
                });
#pragma warning restore 612, 618
        }
    }
}
